config/routes.rb
Rails.application.routes.draw do

  root 'twitter#tomato_search'

  get 'side_bar' => 'side_bar#index'
  get 'side_bar/test_json' => 'side_bar#test_json'

  get 'twitter/tomato' => 'twitter#tomato_search'
  get 'twitter/search_tweets' => 'twitter#search_tweets'
  get 'twitter/history' => 'twitter#history'

  get 'users/sign_in' => 'users#sign_in'
  post 'users/can_create' => 'users#can_create'
  get 'users/log_out' => 'users#log_out'

end

app/models/search.rb
class Search < ActiveRecord::Base
	belongs_to :user
	has_many :tweets
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
	belongs_to :search
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :name,  presence: true, uniqueness: true
	has_many :searches
	has_many :tweets, through: :searches

	def serches_history
		self.searches.inject([]){|arr, search| h = {}; h[:created_at] = search.created_at; h[:tweets] = search.tweets.first(10); arr << h; arr}
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/concerns/twitter_api_calls.rb
module TwitterApiCalls
	require 'rest_client'

	def auth_call
		key = URI::encode(ENV["TWITTER_HONEY_BADGER_KEY"])
    secret = URI::encode(ENV["TWITTER_HONEY_BADGER_SECRET"])
    encoded = Base64.strict_encode64("#{key}:#{secret}")

    res = RestClient::Resource.new "https://api.twitter.com/oauth2/token/"

    options = {}
    options['Authorization'] = "Basic #{encoded}"
    options['Content-Type'] = 'application/x-www-form-urlencoded;charset=UTF-8'

    respond = res.post('grant_type=client_credentials', options)
    token = JSON.parse(respond)["access_token"]
	end

	def search_call(search_me)
		token = auth_call
		res = RestClient::Resource.new URI.escape("https://api.twitter.com/1.1/search/tweets.json?q=#{search_me}&lang=en")

    options = {'Authorization' => "Bearer #{token}"}

    respond = res.get(options)

    keys = %w{created_at text}
    user_keys = %w{profile_image_url_https name screen_name}
    JSON.parse(respond)["statuses"].inject([]){|arr, h| arr << (h.select{|k,v| keys.include? k}).merge(h["user"].select{|kk,vv| user_keys.include? kk}); arr}
	end

end

app/controllers/side_bar_controller.rb
class SideBarController < ApplicationController
  def index
  end

  def test_json()
  	render "side_bar_json.json", layout: false
  end
end

app/controllers/twitter_controller.rb
class TwitterController < ApplicationController
	include TwitterApiCalls
	before_filter :user_redirect?, only: [:tomato_search]
	before_filter :user_ajax?, only: [:search_tweets, :history]

	def tomato_search
	end

	def history
		render :json => @user.serches_history
	end

	def search_tweets
    tweets_arr = search_call("tomato")
    search = Search.create(user: @user)
    tweets_arr.each do |tweet|
    	Tweet.create(
    		search: 											search,
    		user_name: 										tweet["name"],
	      user_screen_name: 						tweet["screen_name"],
	      user_profile_image_url_https: tweet["profile_image_url_https"],
	      tweet_created_at: 						tweet["created_at"],
	      tweet_text: 									tweet["text"]
    	)
    end
    render :json => search.tweets
	end

	private
		def user_redirect?
			redirect_to users_sign_in_path unless user_cookie?
		end

		def user_ajax?
			render :json => {error: "not sign in", url: users_sign_in_url} unless user_cookie?
		end

		def user_cookie?
			@user = cookies[:twitter_user_id] && User.find_by(id: cookies[:twitter_user_id])
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	skip_before_filter :verify_authenticity_token, :only => [:can_create]
	def sign_in
	end

	def can_create
		name =  params["name"]
		success = false 
		if name # no other restriction than have a name
			user = User.find_or_create_by(name: params["name"])
			cookies[:twitter_user_id] = user.id
			success = true
		end
		render json: {success: success, url: twitter_tomato_url}
	end

	def log_out
		cookies.delete :twitter_user_id
		redirect_to users_sign_in_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/side_bar_helper.rb
module SideBarHelper
end

app/helpers/twitter_helper.rb
module TwitterHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Best Title Ever</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/side_bar/index.html.erb
such color, much banana, so yellow, wow

<div id="side-bar-container" ng-app="sideBar">
  <div id="side-bar" class="nav nav-stacked" ng-controller="TestsJsonController as testCntr">
    <h3 class="header-height">
      <span id="header-string">Reports {{testCntr.testsJson.length}}</span>
      <span id="close-side-bar" class="glyphicon glyphicon-remove" onclick="hideSideBar();" title="Close">X</span>
      <span class="glyphicon glyphicon-repeat" ng-click="testCntr.getTests();" title="Bring it on">R</span>
    </h3>
    <div id="search-sort" class="header-height border-bottom-grey">
      <span id="search-box"><input type="text" placeHolder="search report"/></span>
      <span id="sort-tests" class="glyphicon glyphicon-resize-vertical" ng-click="testCntr.filterSwitch();" title="Sort">S</span>
    </div>
    <div id="ul-tests-wrapper">
      <ul id="ul-tests">
        <li class="li-test border-bottom-grey" ng-repeat="test in testCntr.testsJson | orderBy:testCntr.filterBy">
          <div class="column col-left">
            <div class="column test-type">{{test.type}}</div>
            <div class="column test-name" title="{{test.name}}">{{test.name}}</div>
            <div class="test-location">{{test.location}}</div>
          </div>
          <div class="column col-right">
            <div id="test-date">{{testCntr.getDate(test.updated)}}</div>
            <div id="test-time">{{testCntr.getTime(test.updated)}}</div>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>
<div id="side-bar-circle" onclick="showSideBar();" title="Open"><span class="glyphicon glyphicon-eye-open"></span></div>

app/views/twitter/_history.html.erb
<div class="text-center">
	<h4>your search history:</h4>
	<div class="history-list-container" ng-repeat="search in twitterCtrl.search_history | orderBy:'-'">
		<h5>{{twitterCtrl.getDate(search["created_at"]) | date:'dd/MM/yyyy H:mm:ss'}}</h5>
		<ul class="history-list" class="list-group">
		  <li class="list-group-item" ng-repeat="tweet in search['tweets']">
		  	<%= render "tweet_li" %>
		  </li>
		</ul>
	</div>
</div>

app/views/twitter/_search_tweets.html.erb
<div class="text-center">
	<h4>search for Tomato on twitter</h4>
	<button type="button" class="btn btn-red btn-lg" ng-click="twitterCtrl.searchTweets()">Search</button>
	<ul id="tweets-list" class="list-group">
	  <li class="list-group-item" ng-repeat="tweet in twitterCtrl.tweets">
	  	<%= render "tweet_li" %>
	  </li>
	</ul>
</div>

app/views/twitter/_tweet_li.html.erb
<span><img ng-src="{{tweet['user_profile_image_url_https']}}"/></span>
<span>{{tweet["user_name"]}}</span>
<span>@{{tweet["user_screen_name"]}}</span>
<span>{{twitterCtrl.getDate(tweet["tweet_created_at"]) | date:'dd/MM/yyyy'}}</span>
<div>{{tweet["tweet_text"]}}</div>

app/views/twitter/tomato_search.html.erb
<div id="tomato-search-container" class="container twitter-app" ng-app="twitter" ng-controller="TwitterController as twitterCtrl">
  
	<ul class="nav nav-pills">
	  <li role="presentation" ng-class="{'active':twitterCtrl.isTab(0)}" ng-click="twitterCtrl.setTab(0)"><a href="#">Search</a></li>
	  <li role="presentation" ng-class="{'active':twitterCtrl.isTab(1)}" ng-click="twitterCtrl.setTab(1); twitterCtrl.getHistory();"><a href="#">History</a></li>
	  <li role="presentation" class="pull-right"><%= link_to @user.name + " - log out", users_log_out_url %></li>
	</ul>

  <div class="text-center">
    <image-loading-ajax></image-loading-ajax>
    <h1 id="main-header">Tomayto Tomahto</h1>
    <image-loading-ajax></image-loading-ajax>
  </div>

  <div id="search-twitts" ng-show="twitterCtrl.isTab(0)">
  	<%= render "search_tweets"%>
  </div>

  <div id="history" ng-show="twitterCtrl.isTab(1)">
  	<%= render "history"%>
  </div>
</div>

app/views/users/sign_in.html.erb
<div id="sign-in-container" class="container twitter-app" ng-app="users" ng-controller="UsersController as usersCtrl">
	<div class="jumbotron text-center">
	  <h1>Sign in OR Log in</h1>
	  
		<form name="nameForm" class="form-inline" ng-submit="nameForm.$valid && usersCtrl.checkAndRedirect(name)" novalidate>
			<input name="nameInput" type="text" ng-model="name" class="form-control" placeholder="User Name" required/>
			<input type="submit" class="btn btn-red btn-lg"/>
			<div class="invalid-user-name" ng-show="!nameForm.$valid && nameForm.$submitted">invalid user name</div>
		</form>
	</div>
</div>